version: "2"

services:
  app:
    image: dockerlapaz/votacion:go
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_DB: redis:6379
    links:
      - redis
  redis:
    image: redis:alpine